function output = compareMethods(model, toleranceFactor, options)
%COMPAREMETHODS Run cbFBA and pFBA under the same near-optimal tolerance.
%
%   OUTPUT = cbfba.compareMethods(MODEL, FACTOR, OPTIONS) evaluates both
%   formulations with the same validated model, solver display setting, and
%   tolerance factor. The returned comparison table keeps signed minima and
%   maxima as well as historical absolute-endpoint ranges.

    if nargin < 3 || isempty(options)
        options = struct();
    end
    if ~isfield(options, "complexTolerance")
        options.complexTolerance = 1e-12;
    end
    if ~isfield(options, "display")
        options.display = "none";
    end

    model = cbfba.validateModel(model);
    complexModel = cbfba.buildComplexMatrices( ...
        model, ...
        options.complexTolerance);

    commonOptions = struct( ...
        "complexTolerance", options.complexTolerance, ...
        "display", options.display, ...
        "complexModel", complexModel);

    cbResult = cbfba.optimizeFluxRanges( ...
        model, ...
        "cbfba", ...
        toleranceFactor, ...
        commonOptions);

    pfOptions = commonOptions;
    pfOptions.complexModel = [];
    pfResult = cbfba.optimizeFluxRanges( ...
        model, ...
        "pfba", ...
        toleranceFactor, ...
        pfOptions);

    cb = cbResult.ranges;
    pf = pfResult.ranges;

    comparison = table( ...
        cb.ReactionNumber, ...
        cb.ReactionID, ...
        cb.Minimum, ...
        cb.Maximum, ...
        cb.MinAbsoluteEndpoint, ...
        cb.MaxAbsoluteEndpoint, ...
        pf.Minimum, ...
        pf.Maximum, ...
        pf.MinAbsoluteEndpoint, ...
        pf.MaxAbsoluteEndpoint, ...
        'VariableNames', { ...
            'ReactionNumber', ...
            'ReactionID', ...
            'cbFBA_Minimum', ...
            'cbFBA_Maximum', ...
            'cbFBA_MinAbsoluteEndpoint', ...
            'cbFBA_MaxAbsoluteEndpoint', ...
            'pFBA_Minimum', ...
            'pFBA_Maximum', ...
            'pFBA_MinAbsoluteEndpoint', ...
            'pFBA_MaxAbsoluteEndpoint'});

    complexClassification = cbfba.classifyComplexes(complexModel);

    output = struct( ...
        "model", model, ...
        "toleranceFactor", double(toleranceFactor), ...
        "complexModel", complexModel, ...
        "complexClassification", complexClassification, ...
        "cbFBA", cbResult, ...
        "pFBA", pfResult, ...
        "comparison", comparison);
end
